class IssueStatus < ::ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[IssueStatus, ActiveRecord_Relation, Integer]

  module GeneratedAttributeMethods
    def id: () -> Integer

    def id=: (Integer) -> Integer

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ Integer?, Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> Integer?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> Array[Integer?]?

    def id_previously_was: () -> Integer?

    def id_before_last_save: () -> Integer?

    def id_change_to_be_saved: () -> Array[Integer?]?

    def id_in_database: () -> Integer?

    def saved_change_to_id: () -> Array[Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def name: () -> String

    def name=: (String) -> String

    def name?: () -> bool

    def name_changed?: () -> bool

    def name_change: () -> [ String?, String? ]

    def name_will_change!: () -> void

    def name_was: () -> String?

    def name_previously_changed?: () -> bool

    def name_previous_change: () -> Array[String?]?

    def name_previously_was: () -> String?

    def name_before_last_save: () -> String?

    def name_change_to_be_saved: () -> Array[String?]?

    def name_in_database: () -> String?

    def saved_change_to_name: () -> Array[String?]?

    def saved_change_to_name?: () -> bool

    def will_save_change_to_name?: () -> bool

    def restore_name!: () -> void

    def clear_name_change: () -> void

    def is_closed: () -> bool

    def is_closed=: (bool) -> bool

    def is_closed?: () -> bool

    def is_closed_changed?: () -> bool

    def is_closed_change: () -> [ bool?, bool? ]

    def is_closed_will_change!: () -> void

    def is_closed_was: () -> bool?

    def is_closed_previously_changed?: () -> bool

    def is_closed_previous_change: () -> Array[bool?]?

    def is_closed_previously_was: () -> bool?

    def is_closed_before_last_save: () -> bool?

    def is_closed_change_to_be_saved: () -> Array[bool?]?

    def is_closed_in_database: () -> bool?

    def saved_change_to_is_closed: () -> Array[bool?]?

    def saved_change_to_is_closed?: () -> bool

    def will_save_change_to_is_closed?: () -> bool

    def restore_is_closed!: () -> void

    def clear_is_closed_change: () -> void

    def position: () -> Integer?

    def position=: (Integer?) -> Integer?

    def position?: () -> bool

    def position_changed?: () -> bool

    def position_change: () -> [ Integer?, Integer? ]

    def position_will_change!: () -> void

    def position_was: () -> Integer?

    def position_previously_changed?: () -> bool

    def position_previous_change: () -> Array[Integer?]?

    def position_previously_was: () -> Integer?

    def position_before_last_save: () -> Integer?

    def position_change_to_be_saved: () -> Array[Integer?]?

    def position_in_database: () -> Integer?

    def saved_change_to_position: () -> Array[Integer?]?

    def saved_change_to_position?: () -> bool

    def will_save_change_to_position?: () -> bool

    def restore_position!: () -> void

    def clear_position_change: () -> void

    def default_done_ratio: () -> Integer?

    def default_done_ratio=: (Integer?) -> Integer?

    def default_done_ratio?: () -> bool

    def default_done_ratio_changed?: () -> bool

    def default_done_ratio_change: () -> [ Integer?, Integer? ]

    def default_done_ratio_will_change!: () -> void

    def default_done_ratio_was: () -> Integer?

    def default_done_ratio_previously_changed?: () -> bool

    def default_done_ratio_previous_change: () -> Array[Integer?]?

    def default_done_ratio_previously_was: () -> Integer?

    def default_done_ratio_before_last_save: () -> Integer?

    def default_done_ratio_change_to_be_saved: () -> Array[Integer?]?

    def default_done_ratio_in_database: () -> Integer?

    def saved_change_to_default_done_ratio: () -> Array[Integer?]?

    def saved_change_to_default_done_ratio?: () -> bool

    def will_save_change_to_default_done_ratio?: () -> bool

    def restore_default_done_ratio!: () -> void

    def clear_default_done_ratio_change: () -> void

    def description: () -> String?

    def description=: (String?) -> String?

    def description?: () -> bool

    def description_changed?: () -> bool

    def description_change: () -> [ String?, String? ]

    def description_will_change!: () -> void

    def description_was: () -> String?

    def description_previously_changed?: () -> bool

    def description_previous_change: () -> Array[String?]?

    def description_previously_was: () -> String?

    def description_before_last_save: () -> String?

    def description_change_to_be_saved: () -> Array[String?]?

    def description_in_database: () -> String?

    def saved_change_to_description: () -> Array[String?]?

    def saved_change_to_description?: () -> bool

    def will_save_change_to_description?: () -> bool

    def restore_description!: () -> void

    def clear_description_change: () -> void
  end
  include GeneratedAttributeMethods
  def workflows: () -> WorkflowTransition::ActiveRecord_Associations_CollectionProxy
  def workflows=: (WorkflowTransition::ActiveRecord_Associations_CollectionProxy | Array[WorkflowTransition]) -> (WorkflowTransition::ActiveRecord_Associations_CollectionProxy | Array[WorkflowTransition])
  def workflow_ids: () -> Array[Integer]
  def workflow_ids=: (Array[Integer]) -> Array[Integer]
  def workflow_transitions_as_new_status: () -> WorkflowTransition::ActiveRecord_Associations_CollectionProxy
  def workflow_transitions_as_new_status=: (WorkflowTransition::ActiveRecord_Associations_CollectionProxy | Array[WorkflowTransition]) -> (WorkflowTransition::ActiveRecord_Associations_CollectionProxy | Array[WorkflowTransition])
  def workflow_transitions_as_new_status_ids: () -> Array[Integer]
  def workflow_transitions_as_new_status_ids=: (Array[Integer]) -> Array[Integer]

  def self.sorted: () -> ActiveRecord_Relation
  def self.named: (untyped arg) -> ActiveRecord_Relation

  module GeneratedRelationMethods
    def sorted: () -> ActiveRecord_Relation

    def named: (untyped arg) -> ActiveRecord_Relation
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[IssueStatus, Integer]
    include Enumerable[IssueStatus]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[IssueStatus, Integer]
  end
end
