class ApplicationRecord < ActiveRecord::Base
end
class Attachment::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class WikiPage::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Watcher::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Principal::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class WikiContentVersion::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class WikiRedirect::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class CustomValue::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class WorkflowRule::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class MemberRole::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Member::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Message::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class JournalDetail::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class WorkflowTransition::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Issue::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class User::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class EnabledModule::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Journal::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Version::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class TimeEntry::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class TimeEntryActivity::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Query::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Document::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class News::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class IssueCategory::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Board::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Repository::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Changeset::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class IssueRelation::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ImportItem::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Change::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Project::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Role::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Comment::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Enumeration::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class CustomFieldEnumeration::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class EmailAddress::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ActiveRecord::Associations::CollectionProxy < ActiveRecord::Relation
end
class ActiveRecord::Relation < Object
end
module ActiveRecord::Associations
end
