interface _RbsRailsPathHelpers
  def rails_mailers_path: (*untyped) -> String
  def rails_info_properties_path: (*untyped) -> String
  def rails_info_routes_path: (*untyped) -> String
  def rails_info_path: (*untyped) -> String
  def home_path: (*untyped) -> String
  def signin_path: (*untyped) -> String
  def signout_path: (*untyped) -> String
  def account_twofa_confirm_path: (*untyped) -> String
  def account_twofa_resend_path: (*untyped) -> String
  def account_twofa_path: (*untyped) -> String
  def register_path: (*untyped) -> String
  def lost_password_path: (*untyped) -> String
  def account_activate_path: (*untyped) -> String
  def activation_email_path: (*untyped) -> String
  def preview_news_path: (*untyped) -> String
  def preview_issue_path: (*untyped) -> String
  def preview_text_path: (*untyped) -> String
  def new_board_message_path: (*untyped) -> String
  def board_message_path: (*untyped) -> String
  def preview_board_message_path: (*untyped) -> String
  def auto_complete_issues_path: (*untyped) -> String
  def auto_complete_wiki_pages_path: (*untyped) -> String
  def issues_context_menu_path: (*untyped) -> String
  def issue_changes_path: (*untyped) -> String
  def quoted_issue_path: (*untyped) -> String
  def diff_journal_path: (*untyped) -> String
  def edit_journal_path: (*untyped) -> String
  def journal_path: (*untyped) -> String
  def project_gantt_path: (*untyped) -> String
  def issues_gantt_path: (*untyped) -> String
  def project_calendar_path: (*untyped) -> String
  def issues_calendar_path: (*untyped) -> String
  def project_issues_report_path: (*untyped) -> String
  def project_issues_report_details_path: (*untyped) -> String
  def new_issues_import_path: (*untyped) -> String
  def new_time_entries_import_path: (*untyped) -> String
  def new_users_import_path: (*untyped) -> String
  def imports_path: (*untyped) -> String
  def import_path: (*untyped) -> String
  def import_settings_path: (*untyped) -> String
  def import_mapping_path: (*untyped) -> String
  def import_run_path: (*untyped) -> String
  def my_account_path: (*untyped) -> String
  def delete_my_account_path: (*untyped) -> String
  def my_page_path: (*untyped) -> String
  def my_path: (*untyped) -> String
  def my_api_key_path: (*untyped) -> String
  def my_atom_key_path: (*untyped) -> String
  def my_password_path: (*untyped) -> String
  def my_add_block_path: (*untyped) -> String
  def my_remove_block_path: (*untyped) -> String
  def my_order_blocks_path: (*untyped) -> String
  def my_twofa_activate_init_path: (*untyped) -> String
  def my_twofa_select_scheme_path: (*untyped) -> String
  def my_twofa_backup_codes_init_path: (*untyped) -> String
  def my_twofa_backup_codes_confirm_path: (*untyped) -> String
  def my_twofa_backup_codes_create_path: (*untyped) -> String
  def my_twofa_backup_codes_path: (*untyped) -> String
  def users_context_menu_path: (*untyped) -> String
  def bulk_destroy_users_path: (*untyped) -> String
  def bulk_lock_users_path: (*untyped) -> String
  def bulk_unlock_users_path: (*untyped) -> String
  def user_memberships_path: (*untyped) -> String
  def new_user_membership_path: (*untyped) -> String
  def edit_user_membership_path: (*untyped) -> String
  def user_membership_path: (*untyped) -> String
  def user_email_addresses_path: (*untyped) -> String
  def user_email_address_path: (*untyped) -> String
  def users_path: (*untyped) -> String
  def new_user_path: (*untyped) -> String
  def edit_user_path: (*untyped) -> String
  def user_path: (*untyped) -> String
  def watch_path: (*untyped) -> String
  def watchers_watch_path: (*untyped) -> String
  def new_watchers_path: (*untyped) -> String
  def watchers_path: (*untyped) -> String
  def watchers_append_path: (*untyped) -> String
  def watchers_autocomplete_for_mention_path: (*untyped) -> String
  def watchers_autocomplete_for_user_path: (*untyped) -> String
  def autocomplete_projects_path: (*untyped) -> String
  def bulk_destroy_projects_path: (*untyped) -> String
  def settings_project_path: (*untyped) -> String
  def archive_project_path: (*untyped) -> String
  def unarchive_project_path: (*untyped) -> String
  def close_project_path: (*untyped) -> String
  def reopen_project_path: (*untyped) -> String
  def copy_project_path: (*untyped) -> String
  def bookmark_project_path: (*untyped) -> String
  def autocomplete_project_memberships_path: (*untyped) -> String
  def project_memberships_path: (*untyped) -> String
  def new_project_membership_path: (*untyped) -> String
  def edit_membership_path: (*untyped) -> String
  def membership_path: (*untyped) -> String
  def project_enumerations_path: (*untyped) -> String
  def project_copy_issue_path: (*untyped) -> String
  def project_issues_path: (*untyped) -> String
  def new_project_issue_path: (*untyped) -> String
  def project_issues_new_path: (*untyped) -> String
  def project_files_path: (*untyped) -> String
  def new_project_file_path: (*untyped) -> String
  def close_completed_project_versions_path: (*untyped) -> String
  def project_versions_path: (*untyped) -> String
  def new_project_version_path: (*untyped) -> String
  def project_roadmap_path: (*untyped) -> String
  def project_news_index_path: (*untyped) -> String
  def new_project_news_path: (*untyped) -> String
  def report_project_time_entries_path: (*untyped) -> String
  def project_time_entries_path: (*untyped) -> String
  def new_project_time_entry_path: (*untyped) -> String
  def project_queries_path: (*untyped) -> String
  def new_project_query_path: (*untyped) -> String
  def project_issue_categories_path: (*untyped) -> String
  def new_project_issue_category_path: (*untyped) -> String
  def edit_issue_category_path: (*untyped) -> String
  def issue_category_path: (*untyped) -> String
  def project_documents_path: (*untyped) -> String
  def new_project_document_path: (*untyped) -> String
  def project_boards_path: (*untyped) -> String
  def new_project_board_path: (*untyped) -> String
  def edit_project_board_path: (*untyped) -> String
  def project_board_path: (*untyped) -> String
  def committers_repository_path: (*untyped) -> String
  def project_repositories_path: (*untyped) -> String
  def new_project_repository_path: (*untyped) -> String
  def edit_repository_path: (*untyped) -> String
  def repository_path: (*untyped) -> String
  def project_wiki_index_path: (*untyped) -> String
  def rename_project_wiki_page_path: (*untyped) -> String
  def history_project_wiki_page_path: (*untyped) -> String
  def diff_project_wiki_page_path: (*untyped) -> String
  def preview_project_wiki_page_path: (*untyped) -> String
  def protect_project_wiki_page_path: (*untyped) -> String
  def add_attachment_project_wiki_page_path: (*untyped) -> String
  def export_project_wiki_page_index_path: (*untyped) -> String
  def date_index_project_wiki_page_index_path: (*untyped) -> String
  def project_wiki_page_index_path: (*untyped) -> String
  def new_project_wiki_page_path: (*untyped) -> String
  def edit_project_wiki_page_path: (*untyped) -> String
  def project_wiki_page_path: (*untyped) -> String
  def project_wiki_path: (*untyped) -> String
  def projects_path: (*untyped) -> String
  def new_project_path: (*untyped) -> String
  def edit_project_path: (*untyped) -> String
  def project_path: (*untyped) -> String
  def edit_issue_path: (*untyped) -> String
  def tab_issue_path: (*untyped) -> String
  def bulk_edit_issues_path: (*untyped) -> String
  def bulk_update_issues_path: (*untyped) -> String
  def issue_time_entries_path: (*untyped) -> String
  def new_issue_time_entry_path: (*untyped) -> String
  def issue_relations_path: (*untyped) -> String
  def relation_path: (*untyped) -> String
  def issues_path: (*untyped) -> String
  def new_issue_path: (*untyped) -> String
  def issue_path: (*untyped) -> String
  def issues_new_path: (*untyped) -> String
  def queries_path: (*untyped) -> String
  def new_query_path: (*untyped) -> String
  def edit_query_path: (*untyped) -> String
  def query_path: (*untyped) -> String
  def queries_filter_path: (*untyped) -> String
  def news_index_path: (*untyped) -> String
  def new_news_path: (*untyped) -> String
  def edit_news_path: (*untyped) -> String
  def news_path: (*untyped) -> String
  def status_by_version_path: (*untyped) -> String
  def edit_version_path: (*untyped) -> String
  def version_path: (*untyped) -> String
  def add_attachment_document_path: (*untyped) -> String
  def edit_document_path: (*untyped) -> String
  def document_path: (*untyped) -> String
  def time_entries_context_menu_path: (*untyped) -> String
  def edit_time_entry_path: (*untyped) -> String
  def report_time_entries_path: (*untyped) -> String
  def bulk_edit_time_entries_path: (*untyped) -> String
  def bulk_update_time_entries_path: (*untyped) -> String
  def time_entries_path: (*untyped) -> String
  def new_time_entry_path: (*untyped) -> String
  def time_entry_path: (*untyped) -> String
  def time_entries_destroy_path: (*untyped) -> String
  def time_entries_new_path: (*untyped) -> String
  def time_entries_bulk_edit_path: (*untyped) -> String
  def project_activity_path: (*untyped) -> String
  def activity_path: (*untyped) -> String
  def named_attachment_path: (*untyped) -> String
  def download_named_attachment_path: (*untyped) -> String
  def thumbnail_path: (*untyped) -> String
  def attachment_path: (*untyped) -> String
  def object_attachments_edit_path: (*untyped) -> String
  def object_attachments_path: (*untyped) -> String
  def object_attachments_download_path: (*untyped) -> String
  def group_memberships_path: (*untyped) -> String
  def new_group_membership_path: (*untyped) -> String
  def edit_group_membership_path: (*untyped) -> String
  def group_membership_path: (*untyped) -> String
  def autocomplete_for_user_group_path: (*untyped) -> String
  def groups_path: (*untyped) -> String
  def new_group_path: (*untyped) -> String
  def edit_group_path: (*untyped) -> String
  def group_path: (*untyped) -> String
  def new_group_users_path: (*untyped) -> String
  def group_users_path: (*untyped) -> String
  def group_user_path: (*untyped) -> String
  def fields_trackers_path: (*untyped) -> String
  def trackers_path: (*untyped) -> String
  def new_tracker_path: (*untyped) -> String
  def edit_tracker_path: (*untyped) -> String
  def tracker_path: (*untyped) -> String
  def update_issue_done_ratio_issue_statuses_path: (*untyped) -> String
  def issue_statuses_path: (*untyped) -> String
  def new_issue_status_path: (*untyped) -> String
  def edit_issue_status_path: (*untyped) -> String
  def issue_status_path: (*untyped) -> String
  def custom_field_enumerations_path: (*untyped) -> String
  def custom_field_enumeration_path: (*untyped) -> String
  def custom_fields_path: (*untyped) -> String
  def new_custom_field_path: (*untyped) -> String
  def edit_custom_field_path: (*untyped) -> String
  def custom_field_path: (*untyped) -> String
  def permissions_roles_path: (*untyped) -> String
  def roles_path: (*untyped) -> String
  def new_role_path: (*untyped) -> String
  def edit_role_path: (*untyped) -> String
  def role_path: (*untyped) -> String
  def enumerations_path: (*untyped) -> String
  def new_enumeration_path: (*untyped) -> String
  def edit_enumeration_path: (*untyped) -> String
  def enumeration_path: (*untyped) -> String
  def search_path: (*untyped) -> String
  def mail_handler_path: (*untyped) -> String
  def admin_path: (*untyped) -> String
  def admin_projects_path: (*untyped) -> String
  def admin_plugins_path: (*untyped) -> String
  def admin_info_path: (*untyped) -> String
  def test_email_path: (*untyped) -> String
  def admin_default_configuration_path: (*untyped) -> String
  def projects_context_menu_path: (*untyped) -> String
  def try_connection_auth_source_path: (*untyped) -> String
  def autocomplete_for_new_user_auth_sources_path: (*untyped) -> String
  def auth_sources_path: (*untyped) -> String
  def new_auth_source_path: (*untyped) -> String
  def edit_auth_source_path: (*untyped) -> String
  def auth_source_path: (*untyped) -> String
  def edit_workflows_path: (*untyped) -> String
  def workflows_path: (*untyped) -> String
  def permissions_workflows_path: (*untyped) -> String
  def update_permissions_workflows_path: (*untyped) -> String
  def copy_workflows_path: (*untyped) -> String
  def duplicate_workflows_path: (*untyped) -> String
  def settings_path: (*untyped) -> String
  def settings_edit_path: (*untyped) -> String
  def plugin_settings_path: (*untyped) -> String
  def sys_projects_path: (*untyped) -> String
  def sys_fetch_changesets_path: (*untyped) -> String
  def uploads_path: (*untyped) -> String
  def help_wiki_syntax_path: (*untyped) -> String
  def help_code_highlighting_path: (*untyped) -> String
  def rails_mailers_url: (*untyped) -> String
  def rails_info_properties_url: (*untyped) -> String
  def rails_info_routes_url: (*untyped) -> String
  def rails_info_url: (*untyped) -> String
  def home_url: (*untyped) -> String
  def signin_url: (*untyped) -> String
  def signout_url: (*untyped) -> String
  def account_twofa_confirm_url: (*untyped) -> String
  def account_twofa_resend_url: (*untyped) -> String
  def account_twofa_url: (*untyped) -> String
  def register_url: (*untyped) -> String
  def lost_password_url: (*untyped) -> String
  def account_activate_url: (*untyped) -> String
  def activation_email_url: (*untyped) -> String
  def preview_news_url: (*untyped) -> String
  def preview_issue_url: (*untyped) -> String
  def preview_text_url: (*untyped) -> String
  def new_board_message_url: (*untyped) -> String
  def board_message_url: (*untyped) -> String
  def preview_board_message_url: (*untyped) -> String
  def auto_complete_issues_url: (*untyped) -> String
  def auto_complete_wiki_pages_url: (*untyped) -> String
  def issues_context_menu_url: (*untyped) -> String
  def issue_changes_url: (*untyped) -> String
  def quoted_issue_url: (*untyped) -> String
  def diff_journal_url: (*untyped) -> String
  def edit_journal_url: (*untyped) -> String
  def journal_url: (*untyped) -> String
  def project_gantt_url: (*untyped) -> String
  def issues_gantt_url: (*untyped) -> String
  def project_calendar_url: (*untyped) -> String
  def issues_calendar_url: (*untyped) -> String
  def project_issues_report_url: (*untyped) -> String
  def project_issues_report_details_url: (*untyped) -> String
  def new_issues_import_url: (*untyped) -> String
  def new_time_entries_import_url: (*untyped) -> String
  def new_users_import_url: (*untyped) -> String
  def imports_url: (*untyped) -> String
  def import_url: (*untyped) -> String
  def import_settings_url: (*untyped) -> String
  def import_mapping_url: (*untyped) -> String
  def import_run_url: (*untyped) -> String
  def my_account_url: (*untyped) -> String
  def delete_my_account_url: (*untyped) -> String
  def my_page_url: (*untyped) -> String
  def my_url: (*untyped) -> String
  def my_api_key_url: (*untyped) -> String
  def my_atom_key_url: (*untyped) -> String
  def my_password_url: (*untyped) -> String
  def my_add_block_url: (*untyped) -> String
  def my_remove_block_url: (*untyped) -> String
  def my_order_blocks_url: (*untyped) -> String
  def my_twofa_activate_init_url: (*untyped) -> String
  def my_twofa_select_scheme_url: (*untyped) -> String
  def my_twofa_backup_codes_init_url: (*untyped) -> String
  def my_twofa_backup_codes_confirm_url: (*untyped) -> String
  def my_twofa_backup_codes_create_url: (*untyped) -> String
  def my_twofa_backup_codes_url: (*untyped) -> String
  def users_context_menu_url: (*untyped) -> String
  def bulk_destroy_users_url: (*untyped) -> String
  def bulk_lock_users_url: (*untyped) -> String
  def bulk_unlock_users_url: (*untyped) -> String
  def user_memberships_url: (*untyped) -> String
  def new_user_membership_url: (*untyped) -> String
  def edit_user_membership_url: (*untyped) -> String
  def user_membership_url: (*untyped) -> String
  def user_email_addresses_url: (*untyped) -> String
  def user_email_address_url: (*untyped) -> String
  def users_url: (*untyped) -> String
  def new_user_url: (*untyped) -> String
  def edit_user_url: (*untyped) -> String
  def user_url: (*untyped) -> String
  def watch_url: (*untyped) -> String
  def watchers_watch_url: (*untyped) -> String
  def new_watchers_url: (*untyped) -> String
  def watchers_url: (*untyped) -> String
  def watchers_append_url: (*untyped) -> String
  def watchers_autocomplete_for_mention_url: (*untyped) -> String
  def watchers_autocomplete_for_user_url: (*untyped) -> String
  def autocomplete_projects_url: (*untyped) -> String
  def bulk_destroy_projects_url: (*untyped) -> String
  def settings_project_url: (*untyped) -> String
  def archive_project_url: (*untyped) -> String
  def unarchive_project_url: (*untyped) -> String
  def close_project_url: (*untyped) -> String
  def reopen_project_url: (*untyped) -> String
  def copy_project_url: (*untyped) -> String
  def bookmark_project_url: (*untyped) -> String
  def autocomplete_project_memberships_url: (*untyped) -> String
  def project_memberships_url: (*untyped) -> String
  def new_project_membership_url: (*untyped) -> String
  def edit_membership_url: (*untyped) -> String
  def membership_url: (*untyped) -> String
  def project_enumerations_url: (*untyped) -> String
  def project_copy_issue_url: (*untyped) -> String
  def project_issues_url: (*untyped) -> String
  def new_project_issue_url: (*untyped) -> String
  def project_issues_new_url: (*untyped) -> String
  def project_files_url: (*untyped) -> String
  def new_project_file_url: (*untyped) -> String
  def close_completed_project_versions_url: (*untyped) -> String
  def project_versions_url: (*untyped) -> String
  def new_project_version_url: (*untyped) -> String
  def project_roadmap_url: (*untyped) -> String
  def project_news_index_url: (*untyped) -> String
  def new_project_news_url: (*untyped) -> String
  def report_project_time_entries_url: (*untyped) -> String
  def project_time_entries_url: (*untyped) -> String
  def new_project_time_entry_url: (*untyped) -> String
  def project_queries_url: (*untyped) -> String
  def new_project_query_url: (*untyped) -> String
  def project_issue_categories_url: (*untyped) -> String
  def new_project_issue_category_url: (*untyped) -> String
  def edit_issue_category_url: (*untyped) -> String
  def issue_category_url: (*untyped) -> String
  def project_documents_url: (*untyped) -> String
  def new_project_document_url: (*untyped) -> String
  def project_boards_url: (*untyped) -> String
  def new_project_board_url: (*untyped) -> String
  def edit_project_board_url: (*untyped) -> String
  def project_board_url: (*untyped) -> String
  def committers_repository_url: (*untyped) -> String
  def project_repositories_url: (*untyped) -> String
  def new_project_repository_url: (*untyped) -> String
  def edit_repository_url: (*untyped) -> String
  def repository_url: (*untyped) -> String
  def project_wiki_index_url: (*untyped) -> String
  def rename_project_wiki_page_url: (*untyped) -> String
  def history_project_wiki_page_url: (*untyped) -> String
  def diff_project_wiki_page_url: (*untyped) -> String
  def preview_project_wiki_page_url: (*untyped) -> String
  def protect_project_wiki_page_url: (*untyped) -> String
  def add_attachment_project_wiki_page_url: (*untyped) -> String
  def export_project_wiki_page_index_url: (*untyped) -> String
  def date_index_project_wiki_page_index_url: (*untyped) -> String
  def project_wiki_page_index_url: (*untyped) -> String
  def new_project_wiki_page_url: (*untyped) -> String
  def edit_project_wiki_page_url: (*untyped) -> String
  def project_wiki_page_url: (*untyped) -> String
  def project_wiki_url: (*untyped) -> String
  def projects_url: (*untyped) -> String
  def new_project_url: (*untyped) -> String
  def edit_project_url: (*untyped) -> String
  def project_url: (*untyped) -> String
  def edit_issue_url: (*untyped) -> String
  def tab_issue_url: (*untyped) -> String
  def bulk_edit_issues_url: (*untyped) -> String
  def bulk_update_issues_url: (*untyped) -> String
  def issue_time_entries_url: (*untyped) -> String
  def new_issue_time_entry_url: (*untyped) -> String
  def issue_relations_url: (*untyped) -> String
  def relation_url: (*untyped) -> String
  def issues_url: (*untyped) -> String
  def new_issue_url: (*untyped) -> String
  def issue_url: (*untyped) -> String
  def issues_new_url: (*untyped) -> String
  def queries_url: (*untyped) -> String
  def new_query_url: (*untyped) -> String
  def edit_query_url: (*untyped) -> String
  def query_url: (*untyped) -> String
  def queries_filter_url: (*untyped) -> String
  def news_index_url: (*untyped) -> String
  def new_news_url: (*untyped) -> String
  def edit_news_url: (*untyped) -> String
  def news_url: (*untyped) -> String
  def status_by_version_url: (*untyped) -> String
  def edit_version_url: (*untyped) -> String
  def version_url: (*untyped) -> String
  def add_attachment_document_url: (*untyped) -> String
  def edit_document_url: (*untyped) -> String
  def document_url: (*untyped) -> String
  def time_entries_context_menu_url: (*untyped) -> String
  def edit_time_entry_url: (*untyped) -> String
  def report_time_entries_url: (*untyped) -> String
  def bulk_edit_time_entries_url: (*untyped) -> String
  def bulk_update_time_entries_url: (*untyped) -> String
  def time_entries_url: (*untyped) -> String
  def new_time_entry_url: (*untyped) -> String
  def time_entry_url: (*untyped) -> String
  def time_entries_destroy_url: (*untyped) -> String
  def time_entries_new_url: (*untyped) -> String
  def time_entries_bulk_edit_url: (*untyped) -> String
  def project_activity_url: (*untyped) -> String
  def activity_url: (*untyped) -> String
  def named_attachment_url: (*untyped) -> String
  def download_named_attachment_url: (*untyped) -> String
  def thumbnail_url: (*untyped) -> String
  def attachment_url: (*untyped) -> String
  def object_attachments_edit_url: (*untyped) -> String
  def object_attachments_url: (*untyped) -> String
  def object_attachments_download_url: (*untyped) -> String
  def group_memberships_url: (*untyped) -> String
  def new_group_membership_url: (*untyped) -> String
  def edit_group_membership_url: (*untyped) -> String
  def group_membership_url: (*untyped) -> String
  def autocomplete_for_user_group_url: (*untyped) -> String
  def groups_url: (*untyped) -> String
  def new_group_url: (*untyped) -> String
  def edit_group_url: (*untyped) -> String
  def group_url: (*untyped) -> String
  def new_group_users_url: (*untyped) -> String
  def group_users_url: (*untyped) -> String
  def group_user_url: (*untyped) -> String
  def fields_trackers_url: (*untyped) -> String
  def trackers_url: (*untyped) -> String
  def new_tracker_url: (*untyped) -> String
  def edit_tracker_url: (*untyped) -> String
  def tracker_url: (*untyped) -> String
  def update_issue_done_ratio_issue_statuses_url: (*untyped) -> String
  def issue_statuses_url: (*untyped) -> String
  def new_issue_status_url: (*untyped) -> String
  def edit_issue_status_url: (*untyped) -> String
  def issue_status_url: (*untyped) -> String
  def custom_field_enumerations_url: (*untyped) -> String
  def custom_field_enumeration_url: (*untyped) -> String
  def custom_fields_url: (*untyped) -> String
  def new_custom_field_url: (*untyped) -> String
  def edit_custom_field_url: (*untyped) -> String
  def custom_field_url: (*untyped) -> String
  def permissions_roles_url: (*untyped) -> String
  def roles_url: (*untyped) -> String
  def new_role_url: (*untyped) -> String
  def edit_role_url: (*untyped) -> String
  def role_url: (*untyped) -> String
  def enumerations_url: (*untyped) -> String
  def new_enumeration_url: (*untyped) -> String
  def edit_enumeration_url: (*untyped) -> String
  def enumeration_url: (*untyped) -> String
  def search_url: (*untyped) -> String
  def mail_handler_url: (*untyped) -> String
  def admin_url: (*untyped) -> String
  def admin_projects_url: (*untyped) -> String
  def admin_plugins_url: (*untyped) -> String
  def admin_info_url: (*untyped) -> String
  def test_email_url: (*untyped) -> String
  def admin_default_configuration_url: (*untyped) -> String
  def projects_context_menu_url: (*untyped) -> String
  def try_connection_auth_source_url: (*untyped) -> String
  def autocomplete_for_new_user_auth_sources_url: (*untyped) -> String
  def auth_sources_url: (*untyped) -> String
  def new_auth_source_url: (*untyped) -> String
  def edit_auth_source_url: (*untyped) -> String
  def auth_source_url: (*untyped) -> String
  def edit_workflows_url: (*untyped) -> String
  def workflows_url: (*untyped) -> String
  def permissions_workflows_url: (*untyped) -> String
  def update_permissions_workflows_url: (*untyped) -> String
  def copy_workflows_url: (*untyped) -> String
  def duplicate_workflows_url: (*untyped) -> String
  def settings_url: (*untyped) -> String
  def settings_edit_url: (*untyped) -> String
  def plugin_settings_url: (*untyped) -> String
  def sys_projects_url: (*untyped) -> String
  def sys_fetch_changesets_url: (*untyped) -> String
  def uploads_url: (*untyped) -> String
  def help_wiki_syntax_url: (*untyped) -> String
  def help_code_highlighting_url: (*untyped) -> String
end
